---
- name: Create a group and add a user
  hosts: deb1
  become: yes
  tasks:
    - name: Ensure the group exists
      group:
        name: developers
        state: present
    - name: Add user to the group
      user:
        name: test-test
        groups: developers
        append: yes
    - name: Ensure the group exists
      group:
        name: admin
        state: present
    - name: Add user to the group
      user:
        name: test-test
        groups: admin
        append: yes

