---
- hosts: deb1

  tasks:
  - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
     useradd:
       user: name=johnd
       comment: John Doe
       uid: 1040
       group: admin

  - name: Add the user 'james' with a bash shell, appending the group 'admins' and 'developers' to the user's groups
      ansible.builtin.user:
        user: name=james
        shell: /bin/bash
        groups: admins,developers
         append: yes

  - name: Remove the user 'johnd'
      ansible.builtin.user:
      user: name=johnd
      state: absent
      remove: yes

  - name: Create a 2048-bit SSH key for user jsmith in ~jsmith/.ssh/id_rsa
      ansible.builtin.user:
        user: name=jsmith
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa

  - name: Added a consultant whose account you want to expire
      ansible.builtin.user:
        user: name=james18
        shell: /bin/zsh
        groups: developers
        expires: 1422403387

  - name: Starting at Ansible 2.6, modify user, remove expiry time
      ansible.builtin.user:
        user: name=james18
        expires: -1

  - name: Set maximum expiration date for password
      ansible.builtin.user:
        user: name=ram19
        password_expire_max: 10

  - name: Set minimum expiration date for password
      ansible.builtin.user:
        user: name=pushkar15
        password_expire_min: 5

  - name: Set number of warning days for password expiration
      ansible.builtin.user:
        user: name=jane157
        password_expire_warn: 30
