---
- name: Using Conditionals
  hosts: deb2
  tasks:
    - name: Run a command
      command: "date +%H"
      register: current_hour
    - name: Perform action based on time
      debug:
        msg: "Good {{ 'morning' if current_hour.stdout|int < 12 else 'afternoon' }}"
